[package]
name = "geoclue-prometheus-exporter"
version = "0.5.0"
edition = "2021"

[dependencies]
zbus = "5.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
chrono = "0.4"

# Latest metrics crates
metrics = "0.24"
metrics-exporter-prometheus = "0.17"
metrics-process = "2.4.0"  # Latest version available

# For simpler error handling
anyhow = "1.0"

# For command-line argument parsing
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
chrono = "0.4"
